# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a4151c3c2058b447db195ab0faa9d57f947836f93de8c30fc7282b832a7f6020c1a2ccfe1c0ed988759302367a2c9c90ec0087c563ca2cce9af3efc29b3ae11

test:
  secret_key_base: 16c3542a7221232e5a9eed925b357495998b381f5b514014e7c834f3b51d02a752f805d90aa06677d63e68a1925d45e0eafac9115be6ec528f73798fc55ec23c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
